name: Java Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
#        default: "X.Y.Z"
      draft:
        description: "Is it a draft release."
        required: true
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots release:prepare release:perform -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -Dtag=v${{ github.event.inputs.releaseVersion }} -Dusername=${{ github.actor }} -Dpassword=${{ secrets.GITHUB_TOKEN }}  -Darguments="-Dmaven.deploy.skip=true"

      - name: Copy JAR
        run: cp -p target/static-methods-agg-${{ github.event.inputs.releaseVersion }}-jar-with-dependencies.jar static-methods-agg.jar

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: Static Methods Aggregator ${{ github.event.inputs.releaseVersion }}
          tag_name: v${{ github.event.inputs.releaseVersion }}
          files: |
            static-methods-agg.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
